# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4009aa22e421d7f82c3f067d600b2cef1ab80e48b40ef18bf042915246c83c456d07294f47f1e34414fe8b233e069227aaac69dff24b81113d13f32332819f18

test:
  secret_key_base: cb11671c09ceb409d2b74a7a8f479fedcdcdc522952e80017f977445f834e3d70fdbc7a258c98c2e250a18fa0c8cf13269255741aa168b0d810b1c8efcf1d09b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
